### ISSUE TITLE
Possible deadlock or hang in lily

### ISSUE THREAD

**Issue by iand** [filecoin-project/lily#454]
### Describe the bug:

Running `visor watch` hung and also stopped the visor node from syncing

### Steps to Reproduce:

This is what I did:

 - started the daemon
 - started a watch
 - stopped the watch
 - started another watch with a storage
 - stopped the watch
 - started another watch with invalid storage name which fails as expected
 - started another watch with a storage

The command hung and so did the visor daemon. I waited about 10 minutes and then had to kill the daemon manually. Ctrl+C on the watch command didn't work.

**Comment by iand** [comment]
Fixed by #457

**Comment by iand** [comment]
Closed in error

**Comment by frrist** [comment]
Was the storage a database or csv file? 

Is it safe for me to assume the watch started without storage were using `NullStorage`?

**Comment by frrist** [comment]
Was able to repro and take a stack dump on the client side:
```
^\SIGQUIT: quit
PC=0x5a8801 m=0 sigcode=128

goroutine 0 [idle]:
runtime.futex(0x7682488, 0x80, 0x0, 0x0, 0x7ffc00000000, 0x5a83dc, 0x1ce6b5, 0x1358db0f, 0x7ffce2d6f358, 0x541dbf, ...)
        /home/ubuntu/.apps/go/src/runtime/sys_linux_amd64.s:587 +0x21
runtime.futexsleep(0x7682488, 0x0, 0xffffffffffffffff)
        /home/ubuntu/.apps/go/src/runtime/os_linux.go:45 +0x46
runtime.notesleep(0x7682488)
        /home/ubuntu/.apps/go/src/runtime/lock_futex.go:159 +0x9f
runtime.stopm()
        /home/ubuntu/.apps/go/src/runtime/proc.go:1924 +0xc5
runtime.findrunnable(0xc000065000, 0x0)
        /home/ubuntu/.apps/go/src/runtime/proc.go:2485 +0xa7f
runtime.schedule()
        /home/ubuntu/.apps/go/src/runtime/proc.go:2683 +0x2d7
runtime.park_m(0xc000280c00)
        /home/ubuntu/.apps/go/src/runtime/proc.go:2851 +0x9d
runtime.mcall(0x0)
        /home/ubuntu/.apps/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [select, 1 minutes]:
github.com/filecoin-project/go-jsonrpc.websocketClient.func2(0x445ece0, 0xc0002939b0, 0x3ddeafa, 0x3, 0xc0002961b0, 0xc0002983a0, 0x12, 0xc000293800, 0x1, 0x1, ...)
        /home/ubuntu/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/client.go:233 +0x23e
github.com/filecoin-project/go-jsonrpc.(*client).sendRequest(0xc0002932f0, 0x445ece0, 0xc0002939b0, 0x3ddeafa, 0x3, 0xc0002961b0, 0xc0002983a0, 0x12, 0xc000293800, 0x1, ...)
        /home/ubuntu/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/client.go:414 +0x198
github.com/filecoin-project/go-jsonrpc.(*rpcFunc).handleRpcCall(0xc0002b4140, 0xc0002937d0, 0x2, 0x2, 0x0, 0x0, 0x0)
        /home/ubuntu/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/client.go:526 +0x5ff
reflect.callReflect(0xc000293530, 0xc001bbfb50, 0xc001bbfb38)
        /home/ubuntu/.apps/go/src/reflect/value.go:565 +0x32a
reflect.makeFuncStub(0x445ec20, 0xc001303200, 0xc000290900, 0x7703c48, 0x0, 0x0, 0xc001bbfc70, 0x278dd9c, 0xc000276000, 0x445ec20, ...)
        /home/ubuntu/.apps/go/src/reflect/asm_amd64.s:20 +0x42
github.com/filecoin-project/sentinel-visor/lens/lily.(*LilyAPIStruct).LilyWatch(0xc000276000, 0x445ec20, 0xc001303200, 0xc000290900, 0x0, 0x0, 0x44bfd60)
        /home/ubuntu/src/github.com/filecoin-project/sentinel-visor/lens/lily/struct.go:44 +0x4b
github.com/filecoin-project/sentinel-visor/commands.glob..func8(0xc0013031c0, 0x0, 0x0)
        /home/ubuntu/src/github.com/filecoin-project/sentinel-visor/commands/watch.go:114 +0x35c
github.com/urfave/cli/v2.(*Command).Run(0x74e77c0, 0xc001302f40, 0x0, 0x0)
        /home/ubuntu/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4ed
github.com/urfave/cli/v2.(*App).RunContext(0xc000dd4820, 0x445ec20, 0xc001302ac0, 0xc00004e0a0, 0x5, 0x5, 0x0, 0x0)
        /home/ubuntu/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81f
main.main()
        /home/ubuntu/src/github.com/filecoin-project/sentinel-visor/main.go:115 +0xb92

goroutine 6 [select, 1 minutes]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc0000b7bf0)
        /home/ubuntu/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:71 +0x128
created by github.com/ipfs/go-log/writer.NewMirrorWriter
        /home/ubuntu/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:36 +0xb9

goroutine 7 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0001ba180)
        /home/ubuntu/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:276 +0x105
created by go.opencensus.io/stats/view.init.0
        /home/ubuntu/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:34 +0x68

goroutine 28 [select, 1 minutes]:
main.main.func1(0xc000223e90, 0x445ec20, 0xc001302ac0)
        /home/ubuntu/src/github.com/filecoin-project/sentinel-visor/main.go:28 +0x145
created by main.main
        /home/ubuntu/src/github.com/filecoin-project/sentinel-visor/main.go:25 +0xac

goroutine 37 [syscall, 1 minutes]:
os/signal.signal_recv(0x5a6981)
        /home/ubuntu/.apps/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
        /home/ubuntu/.apps/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /home/ubuntu/.apps/go/src/os/signal/signal.go:150 +0x45

goroutine 29 [chan receive, 1 minutes]:
github.com/filecoin-project/lotus/cli/util.ReqContext.func1(0xc00131d140, 0xc0013684a0)
        /home/ubuntu/pkg/mod/github.com/filecoin-project/lotus@v1.6.1-0.20210413121043-9e600eac7e8e/cli/util/api.go:268 +0x34
created by github.com/filecoin-project/lotus/cli/util.ReqContext
        /home/ubuntu/pkg/mod/github.com/filecoin-project/lotus@v1.6.1-0.20210413121043-9e600eac7e8e/cli/util/api.go:267 +0x108

goroutine 39 [select]:
github.com/filecoin-project/go-jsonrpc.(*wsConn).handleWsConn(0xc000dfe240, 0x445ec20, 0xc001303200)
        /home/ubuntu/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:603 +0x468
created by github.com/filecoin-project/go-jsonrpc.websocketClient
        /home/ubuntu/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/client.go:262 +0x2cf

goroutine 40 [select]:
github.com/filecoin-project/go-jsonrpc.(*wsConn).setupPings.func3(0xc000dfe240, 0xc0002a6600)
        /home/ubuntu/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:494 +0xc6
created by github.com/filecoin-project/go-jsonrpc.(*wsConn).setupPings
        /home/ubuntu/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:492 +0xcf

goroutine 41 [IO wait]:
internal/poll.runtime_pollWait(0x7fb97c3c2cb8, 0x72, 0x4407de0)
        /home/ubuntu/.apps/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0002b8218, 0x72, 0x4407d00, 0x7525110, 0x0)
        /home/ubuntu/.apps/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /home/ubuntu/.apps/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0002b8200, 0xc0002c2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/ubuntu/.apps/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc0002b8200, 0xc0002c2000, 0x1000, 0x1000, 0xc00008dce0, 0x53babc, 0xc000280a80)
        /home/ubuntu/.apps/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0005e40d0, 0xc0002c2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/ubuntu/.apps/go/src/net/net.go:182 +0x8e
bufio.(*Reader).fill(0xc000290ae0)
        /home/ubuntu/.apps/go/src/bufio/bufio.go:101 +0x105
bufio.(*Reader).Peek(0xc000290ae0, 0x2, 0xc0002a6540, 0xc00008ddc0, 0x0, 0x13943d8, 0x1)
        /home/ubuntu/.apps/go/src/bufio/bufio.go:139 +0x4f
github.com/gorilla/websocket.(*Conn).read(0xc0002c0160, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:370 +0x45
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0002c0160, 0xa, 0x0, 0x0)
        /home/ubuntu/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:798 +0x5c
github.com/gorilla/websocket.(*Conn).NextReader(0xc0002c0160, 0xc01836989c3f6324, 0x701085244, 0x76800a0, 0x0, 0x0)
        /home/ubuntu/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:980 +0x8f
github.com/filecoin-project/go-jsonrpc.(*wsConn).nextMessage(0xc000dfe240)
        /home/ubuntu/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:100 +0x5a
created by github.com/filecoin-project/go-jsonrpc.(*wsConn).handleWsConn
        /home/ubuntu/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:588 +0x2b1

rax    0xca
rbx    0x7682340
rcx    0x5a8803
rdx    0x0
rdi    0x7682488
rsi    0x80
rbp    0x7ffce2d6f320
rsp    0x7ffce2d6f2d8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x3
r13    0x7680f00
r14    0xc0002a6600
r15    0x0
rip    0x5a8801
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by frrist** [comment]
Heres from the daemon side (its kind of a lot): 
[stackdump.txt](https://github.com/filecoin-project/sentinel-visor/files/6352979/stackdump.txt)

relevant lines from lily:
```
goroutine 66336 [semacquire]:
sync.runtime_SemacquireMutex(0xc048501564, 0xc048501700, 0x1)                                                                                                                                                                                                                                                                   
        /home/ubuntu/.apps/go/src/runtime/sema.go:71 +0x47                                                                                                                                                                                                                                                                      
sync.(*Mutex).lockSlow(0xc048501560)                                                                                                                                                                                                                                                                                            
        /home/ubuntu/.apps/go/src/sync/mutex.go:138 +0x105                                                                                                                                                                                                                                                                      
sync.(*Mutex).Lock(...)                                                                                                                                                                                                                                                                                                         
        /home/ubuntu/.apps/go/src/sync/mutex.go:81                                                                                                                                                                                                                                                                              
github.com/filecoin-project/sentinel-visor/schedule.(*Scheduler).Jobs(0xc03252f200, 0x0, 0x0, 0x0)                                                                                                                                                                                                                              
        /home/ubuntu/src/github.com/filecoin-project/sentinel-visor/schedule/scheduler.go:264 +0x38e                                                                                                                                                                                                                            
github.com/filecoin-project/sentinel-visor/lens/lily.(*LilyNodeAPI).LilyJobList(0xc0000be1a0, 0x445ece0, 0xc0387d25d0, 0x0, 0x0, 0x0, 0x0, 0x0)                                                                                                                                                                                 
        /home/ubuntu/src/github.com/filecoin-project/sentinel-visor/lens/lily/impl.go:124 +0x32                                                                                                                                                                                                                                 
reflect.Value.call(0x3dc97a0, 0xc0000be1a0, 0x6e13, 0x3de0cbc, 0x4, 0xc03b07f680, 0x1, 0x1, 0x3af94e0, 0xc0394e1f00, ...)                                                                                                                                                                                                       
        /home/ubuntu/.apps/go/src/reflect/value.go:476 +0x8c7                                                                                                                                                                                                                                                                   
reflect.Value.Call(0x3dc97a0, 0xc0000be1a0, 0x6e13, 0xc03b07f680, 0x1, 0x1, 0xc0387d25d0, 0x0, 0x0)                                                                                                                                                                                                                             
        /home/ubuntu/.apps/go/src/reflect/value.go:337 +0xb9                                                                                                                                                                                                                                                                    
github.com/filecoin-project/sentinel-visor/commands/util.proxy.func1(0xc03b07f680, 0x1, 0x1, 0x0, 0x0, 0x0)                                                                                                                                                                                                                     
        /home/ubuntu/src/github.com/filecoin-project/sentinel-visor/commands/util/rpc.go:66 +0x29e                                                                                                                                                                                                                              
reflect.callReflect(0xc0002cc6c0, 0xc05cb290d0, 0xc05cb290b8)                                                                                                                                                                                                                                                                   
        /home/ubuntu/.apps/go/src/reflect/value.go:565 +0x32a                                                                                                                                                                                                                                                                   
reflect.makeFuncStub(0x445ece0, 0xc0387d2540, 0x7fa22c9047d0, 0xc0394e1e80, 0x18, 0xc000100400, 0x54acfb, 0xc05cb29158, 0x5a4ffe, 0xc00030f1e0, ...)                                                                                                                                                                            
        /home/ubuntu/.apps/go/src/reflect/asm_amd64.s:20 +0x42                                                                                                                                                                                                                                                                  
github.com/filecoin-project/sentinel-visor/lens/lily.(*LilyAPIStruct).LilyJobList(0xc00030f1e0, 0x445ece0, 0xc0387d2540, 0x0, 0x0, 0x0, 0x0, 0x0)                                                                                                                                                                               
        /home/ubuntu/src/github.com/filecoin-project/sentinel-visor/lens/lily/struct.go:60 +0x42                                                                                                                                                                                                                                
reflect.Value.call(0x3dc87e0, 0xc00030f1e0, 0x6e13, 0x3de0cbc, 0x4, 0xc03b07f660, 0x1, 0x1, 0x4, 0x1, ...)                                                                                                                                                                                                                      
        /home/ubuntu/.apps/go/src/reflect/value.go:476 +0x8c7                                                                                                                                                                                                                                                                   
reflect.Value.Call(0x3dc87e0, 0xc00030f1e0, 0x6e13, 0xc03b07f660, 0x1, 0x1, 0x4, 0x7fa080590201, 0x10)                                                                                                                                                                                                                          
        /home/ubuntu/.apps/go/src/reflect/value.go:337 +0xb9                                                                                                                                                                                                                                                                    
github.com/filecoin-project/go-jsonrpc/auth.PermissionedProxy.func1(0xc03b07f660, 0x1, 0x1, 0xc03b07f660, 0x1ee800, 0x3881820)                                                                                                                                                                                                  
        /home/ubuntu/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/auth/auth.go:62 +0x533                                                                                                                                                                                                 
reflect.callReflect(0xc0002cc900, 0xc05cb29640, 0xc05cb29628)                                                                                                                                                                                                                                                                   
        /home/ubuntu/.apps/go/src/reflect/value.go:565 +0x32a                                                                                                                                                                                                                                                                   
reflect.makeFuncStub(0x445ece0, 0xc0387d2540, 0xc0387d2540, 0xc0394e1e40, 0x18, 0xc000100400, 0x0, 0xc05cb296c8, 0x5a4ffe, 0xc00030f380, ...)                                                                                                                                                                                   
        /home/ubuntu/.apps/go/src/reflect/asm_amd64.s:20 +0x42                                                                                                                                                                                                                                                                  
github.com/filecoin-project/sentinel-visor/lens/lily.(*LilyAPIStruct).LilyJobList(0xc00030f380, 0x445ece0, 0xc0387d2540, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/src/github.com/filecoin-project/sentinel-visor/lens/lily/struct.go:60 +0x42
reflect.Value.call(0xc03252fc80, 0xc000305058, 0x13, 0x3de0cbc, 0x4, 0xc0387d2570, 0x2, 0x2, 0x30, 0x3dc3780, ...)
        /home/ubuntu/.apps/go/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0xc03252fc80, 0xc000305058, 0x13, 0xc0387d2570, 0x2, 0x2, 0x60000c0000df600, 0xc0000df600, 0xc05cb299e0)
        /home/ubuntu/.apps/go/src/reflect/value.go:337 +0xb9
github.com/filecoin-project/go-jsonrpc.doCall(0xc0569d54a0, 0x14, 0xc03252fc80, 0xc000305058, 0x13, 0xc0387d2570, 0x2, 0x2, 0x0, 0x0, ...)
        /home/ubuntu/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/handler.go:162 +0xdc
github.com/filecoin-project/go-jsonrpc.(*RPCServer).handle(0xc032547c00, 0x445ece0, 0xc0387d24b0, 0xc04dee95b8, 0x3, 0xc04dee95c0, 0xc0569d54a0, 0x14, 0x7703c48, 0x0, ...)
        /home/ubuntu/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/handler.go:259 +0xe85
created by github.com/filecoin-project/go-jsonrpc.(*wsConn).handleCall
        /home/ubuntu/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:424 +0x28f
        ```
Looks like we are blocking on a job lock here.

**Comment by frrist** [comment]
One deadlock here on the error case: https://github.com/filecoin-project/sentinel-visor/blob/cdd50599a57321f74258dd099b014f0901f87e5b/schedule/scheduler.go#L204-L208

**Comment by placer14** [comment]
Here's another deadlock detection on `analysis-v3-lily-0` running in staging EKS `ntwk-mainnet-sentinel` namespace. Error reported in `lily job list`:

`index: notify tipset: persist result (miner_fee_debt.model.PersistableList): persisting model.PersistableList: persisting model: ERROR #40P01 deadlock detected`
